Unable to init server: Could not connect: Connection refused
Unable to init server: Não foi possível conectar: Connection refused

(makeGraphs.py:278990): Gdk-CRITICAL **: 03:23:12.718: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
